try {
    hello()
} catch (error){
    console.log(error);
}

// Nuevo metodo

try {
    anotherFn();
} catch {
    console.log('Esto es un error');
}
